#ifndef _IN_MD_AUDIO_ALIASES_H
#define _IN_MD_AUDIO_ALIASES_H

/*
 * Perfect Dark Renaissance-owned external audio trigger keys and filenames.
 *
 * Music keys are extensionless ext_music lookup keys.
 * SFX names are ext_sfx filenames.
 */

#define MD_MUSIC_KEY_OPENING_COMPANY_LOGOS "opening_company_logos"
#define MD_MUSIC_KEY_MAIN_TITLE_LOGO       "main_title_logo"
#define MD_MUSIC_KEY_MAIN_MENU             "main_menu"
#define MD_MUSIC_KEY_COMBAT_SIM_MENU       "combat_sim_menu"
#define MD_MUSIC_KEY_TERMINATION_MENU       "termination_menu"
#define MD_MUSIC_KEY_COMBAT_SIM_COMPLETE   "combat_sim_complete"
#define MD_MUSIC_KEY_MULTIPLAYER_DEATH     "multiplayer_death"
#define MD_MUSIC_KEY_LMS_WIN               "last_man_standing_win"
#define MD_MUSIC_KEY_LMS_LOSE              "last_man_standing_lose"
#define MD_MUSIC_KEY_TERMINATION_WIN        "termination_win"
#define MD_MUSIC_KEY_TERMINATION_LOSE       "termination_lose"
#define MD_MUSIC_KEY_MISSION_SUCCESS       "mission_success"
#define MD_MUSIC_KEY_MISSION_UNKNOWN       "mission_unknown"
#define MD_MUSIC_KEY_MISSION_FAILED        "mission_failed"
#define MD_MUSIC_KEY_PAUSE_MENU            "pause_menu"
#define MD_MUSIC_KEY_SOLO_DEATH            "solo_death"
#define MD_MUSIC_KEY_CI_TRAINING           "ci_training"

#define MD_MUSIC_KEY_MP_DARK_COMBAT        "mp_track_dark_combat"
#define MD_MUSIC_KEY_MP_SKEDAR_MYSTERY     "mp_track_skedar_mystery"
#define MD_MUSIC_KEY_MP_CI_OPERATIVE       "mp_track_ci_operative"
#define MD_MUSIC_KEY_MP_DATADYNE_ACTION    "mp_track_datadyne_action"
#define MD_MUSIC_KEY_MP_MAIAN_TEARS        "mp_track_maian_tears"
#define MD_MUSIC_KEY_MP_ALIEN_CONFLICT     "mp_track_alien_conflict"
#define MD_MUSIC_KEY_MP_CI                 "mp_track_carrington_institute"
#define MD_MUSIC_KEY_MP_DD_CENTRAL         "mp_track_dd_central"
#define MD_MUSIC_KEY_MP_DD_CENTRAL_X       "mp_track_dd_central_x"
#define MD_MUSIC_KEY_MP_DD_RESEARCH        "mp_track_dd_research"
#define MD_MUSIC_KEY_MP_DD_RESEARCH_X      "mp_track_dd_research_x"
#define MD_MUSIC_KEY_MP_DD_EXTRACTION      "mp_track_dd_extraction"
#define MD_MUSIC_KEY_MP_DD_EXTRACTION_X    "mp_track_dd_extraction_x"
#define MD_MUSIC_KEY_MP_VILLA              "mp_track_carrington_villa"
#define MD_MUSIC_KEY_MP_VILLA_X            "mp_track_carrington_villa_x"
#define MD_MUSIC_KEY_MP_CHICAGO            "mp_track_chicago"
#define MD_MUSIC_KEY_MP_CHICAGO_X          "mp_track_chicago_x"
#define MD_MUSIC_KEY_MP_G5                 "mp_track_g5_building"
#define MD_MUSIC_KEY_MP_G5_X               "mp_track_g5_building_x"
#define MD_MUSIC_KEY_MP_A51_INFILTRATION   "mp_track_a51_infiltration"
#define MD_MUSIC_KEY_MP_A51_INFILTRATION_X "mp_track_a51_infiltration_x"
#define MD_MUSIC_KEY_MP_A51_RESCUE         "mp_track_a51_rescue"
#define MD_MUSIC_KEY_MP_A51_RESCUE_X       "mp_track_a51_rescue_x"
#define MD_MUSIC_KEY_MP_A51_ESCAPE         "mp_track_a51_escape"
#define MD_MUSIC_KEY_MP_A51_ESCAPE_X       "mp_track_a51_escape_x"
#define MD_MUSIC_KEY_MP_AIR_BASE           "mp_track_air_base"
#define MD_MUSIC_KEY_MP_AIR_BASE_X         "mp_track_air_base_x"
#define MD_MUSIC_KEY_MP_AIR_FORCE_ONE      "mp_track_air_force_one"
#define MD_MUSIC_KEY_MP_AIR_FORCE_ONE_X    "mp_track_air_force_one_x"
#define MD_MUSIC_KEY_MP_CRASH_SITE         "mp_track_crash_site"
#define MD_MUSIC_KEY_MP_CRASH_SITE_X       "mp_track_crash_site_x"
#define MD_MUSIC_KEY_MP_PELAGIC_II         "mp_track_pelagic_ii"
#define MD_MUSIC_KEY_MP_PELAGIC_II_X       "mp_track_pelagic_ii_x"
#define MD_MUSIC_KEY_MP_DEEP_SEA           "mp_track_deep_sea"
#define MD_MUSIC_KEY_MP_DEEP_SEA_X         "mp_track_deep_sea_x"
#define MD_MUSIC_KEY_MP_INSTITUTE_DEFENSE  "mp_track_institute_defense"
#define MD_MUSIC_KEY_MP_INSTITUTE_DEFENSE_X "mp_track_institute_defense_x"
#define MD_MUSIC_KEY_MP_ATTACK_SHIP        "mp_track_attack_ship"
#define MD_MUSIC_KEY_MP_ATTACK_SHIP_X      "mp_track_attack_ship_x"
#define MD_MUSIC_KEY_MP_SKEDAR_RUINS       "mp_track_skedar_ruins"
#define MD_MUSIC_KEY_MP_SKEDAR_RUINS_X     "mp_track_skedar_ruins_x"
#define MD_MUSIC_KEY_MP_END_CREDITS        "mp_track_end_credits"
#define MD_MUSIC_KEY_MP_SKEDAR_WARRIOR     "mp_track_skedar_warrior"

#define MD_SFX_FALCON_SILENCER_TOGGLE      "SFX_0022_falcon_silencer_toggle.wav"
#define MD_SFX_MATRIX85_FIRE                "gun-shot-matrix85-01.wav"
#define MD_SFX_BODY_HIT_01                 "bullet_body_hit_01.wav"
#define MD_SFX_BODY_HIT_02                 "bullet_body_hit_02.wav"
#define MD_SFX_BODY_HIT_03                 "bullet_body_hit_03.wav"
#define MD_SFX_BODY_HIT_04                 "bullet_body_hit_04.wav"
#define MD_SFX_BODY_HIT_05                 "bullet_body_hit_05.wav"
#define MD_SFX_BODY_HIT_06                 "bullet_body_hit_06.wav"
#define MD_SFX_METAL_HIT_01                "bullet_metal_hit_01.wav"
#define MD_SFX_METAL_HIT_02                "bullet_metal_hit_02.wav"
#define MD_SFX_METAL_HIT_03                "bullet_metal_hit_03.wav"
#define MD_SFX_METAL_HIT_04                "bullet_metal_hit_04.wav"
#define MD_SFX_METAL_HIT_05                "bullet_metal_hit_05.wav"
#define MD_SFX_METAL_HIT_06                "bullet_metal_hit_06.wav"
#define MD_SFX_TILE_HIT_01                 "tile_hit_01.wav"
#define MD_SFX_WALL_HIT_01                 "wall_hit_01.wav"
#define MD_SFX_WALL_HIT_02                 "wall_hit_02.wav"
#define MD_SFX_WALL_HIT_03                 "wall_hit_03.wav"
#define MD_SFX_WALL_HIT_04                 "wall_hit_04.wav"
#define MD_SFX_WALL_HIT_05                 "wall_hit_05.wav"
#define MD_SFX_WALL_HIT_06                 "wall_hit_06.wav"
#define MD_SFX_WALL_HIT_07                 "wall_hit_07.wav"
#define MD_SFX_WALL_HIT_08                 "wall_hit_08.wav"
#define MD_SFX_WALL_HIT_09                 "wall_hit_09.wav"
#define MD_SFX_WALL_HIT_10                 "wall_hit_10.wav"
#define MD_SFX_WALL_HIT_11                 "wall_hit_11.wav"
#define MD_SFX_WALL_HIT_12                 "wall_hit_12.wav"
#define MD_SFX_WALL_HIT_13                 "wall_hit_13.wav"
#define MD_SFX_WALL_HIT_14                 "wall_hit_14.wav"
#define MD_SFX_DUST_01                     "dust_01.wav"
#define MD_SFX_DUST_02                     "dust_02.wav"
#define MD_SFX_DUST_03                     "dust_03.wav"
#define MD_SFX_DUST_04                     "dust_04.wav"
#define MD_SFX_DOOR_EXPLOSION_DEBRIS       "door_explosion_debris.wav"

#endif
