#ifndef _IN_MD_SCENARIO_ALIASES_H
#define _IN_MD_SCENARIO_ALIASES_H

#include "constants.h"
#include "lang.h"

/*
 * PERFECT DARK RENAISSANCE author-facing multiplayer scenario aliases.
 *
 * These are compatibility handles: the engine still stores legacy
 * MPSCENARIO_* ids, but mod-authored menu/setup code should prefer the
 * MD_MPSCENARIO_* names where an alias exists.
 */

#define MD_MPSCENARIO_COMBAT              MPSCENARIO_COMBAT
#define MD_MPSCENARIO_HOLD_THE_BRIEFCASE  MPSCENARIO_HOLDTHEBRIEFCASE
#define MD_MPSCENARIO_HACKER_CENTRAL      MPSCENARIO_HACKERCENTRAL
#define MD_MPSCENARIO_POP_A_CAP           MPSCENARIO_POPACAP
#define MD_MPSCENARIO_KING_OF_THE_HILL    MPSCENARIO_KINGOFTHEHILL
#define MD_MPSCENARIO_CAPTURE_THE_CASE    MPSCENARIO_CAPTURETHECASE
#define MD_MPSCENARIO_RESCUE_HOSTAGES     MPSCENARIO_RESCUEHOSTAGES
#define MD_MPSCENARIO_LAST_MAN_STANDING   MPSCENARIO_LASTMANSTANDING
#define MD_MPSCENARIO_TERMINATION          MPSCENARIO_TERMINATION

/*
 * Scenario menu text ids.
 *
 * Legacy language ids remain the storage mechanism for now. These aliases make
 * menu ownership read as PERFECT DARK RENAISSANCE scenario data instead of raw L_MPMENU ids.
 */

#define MD_MPSCENARIO_TEXT_COMBAT_NAME             L_MPMENU_246
#define MD_MPSCENARIO_TEXT_BRIEFCASE_NAME          L_MPMENU_247
#define MD_MPSCENARIO_TEXT_HACKER_CENTRAL_NAME     L_MPMENU_248
#define MD_MPSCENARIO_TEXT_POP_A_CAP_NAME          L_MPMENU_249
#define MD_MPSCENARIO_TEXT_KING_OF_THE_HILL_NAME   L_MPMENU_250
#define MD_MPSCENARIO_TEXT_CAPTURE_THE_CASE_NAME   L_MPMENU_251

#define MD_MPSCENARIO_TEXT_COMBAT_SHORT            L_MPMENU_253
#define MD_MPSCENARIO_TEXT_BRIEFCASE_SHORT         L_MPMENU_254
#define MD_MPSCENARIO_TEXT_HACKER_CENTRAL_SHORT    L_MPMENU_255
#define MD_MPSCENARIO_TEXT_POP_A_CAP_SHORT         L_MPMENU_256
#define MD_MPSCENARIO_TEXT_KING_OF_THE_HILL_SHORT  L_MPMENU_257
#define MD_MPSCENARIO_TEXT_CAPTURE_THE_CASE_SHORT  L_MPMENU_258

#define MD_MPSCENARIO_GROUP_FREE_FOR_ALL           L_MPMENU_244
#define MD_MPSCENARIO_GROUP_TEAMWORK               L_MPMENU_245

#define MD_MPSCENARIO_TEXT_RESCUE_HOSTAGES_NAME    L_MPMENU_339
#define MD_MPSCENARIO_TEXT_RESCUE_HOSTAGES_SHORT   L_MPMENU_340
#define MD_MPSCENARIO_TEXT_LAST_MAN_STANDING_NAME  L_MPMENU_341
#define MD_MPSCENARIO_TEXT_LAST_MAN_STANDING_SHORT L_MPMENU_342
#define MD_MPSCENARIO_TEXT_TERMINATION_NAME         L_MPMENU_343
#define MD_MPSCENARIO_TEXT_TERMINATION_SHORT        L_MPMENU_343
#define MD_MPSCENARIO_GROUP_PVE_MODES              L_MPMENU_344

#endif
