#!/usr/bin/env python3

import os
import subprocess
import sys


def main():
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    tool = os.path.join(repo, "tools", "regenerate_lang_asset")
    args = sys.argv[1:]

    if "--lang" not in args:
        args = ["--lang", "en"] + args

    return subprocess.run([tool, "gun"] + args, cwd=repo).returncode


if __name__ == "__main__":
    raise SystemExit(main())
